// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlneuhivxmpiasjmmryi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbmV1aGl2eG1waWFzam1tcnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0ODAwMjEsImV4cCI6MjA3NTA1NjAyMX0.s0sdVp1cePTAdj4SDO_Dkj3R5LQy-mkTcofiopbA5CU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});